# Generated by Django 4.2.4 on 2023-08-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('text', models.TextField()),
                ('output', models.BooleanField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
