# Generated by Django 4.2.4 on 2023-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('text', models.TextField()),
                ('predicted', models.BooleanField(default=False)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('text', models.TextField()),
                ('output', models.BooleanField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('user_count', models.IntegerField(default=0)),
            ],
        ),
    ]
