# Generated by Django 4.2.4 on 2023-08-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevant',
            fields=[
                ('text', models.TextField()),
                ('is_spam', models.BooleanField()),
                ('is_relevant', models.BooleanField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('user_count', models.IntegerField(default=0)),
            ],
        ),
    ]
