# Generated by Django 4.2.4 on 2023-08-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_relevant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relevant',
            old_name='is_relevant',
            new_name='relevant',
        ),
        migrations.RenameField(
            model_name='relevant',
            old_name='is_spam',
            new_name='spam',
        ),
    ]
