# Generated by Django 4.2.4 on 2023-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_relevant_date_alter_result_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorical',
            fields=[
                ('text', models.TextField()),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('category', models.IntegerField()),
            ],
        ),
    ]
